services:
  - docker

jobs:
  include:
    - stage: Linting and sanity tests
      name: Lint script with shellcheck
      script: ./tests/lint.shellcheck.sh
    - name: Lint dockerfile
      script: bash ./tests/lint.hadolint.sh
    - name: Test simple backup and exclusion scenario with tar
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y
          tree
          coreutils
      env:
        SRC_DIR: /tmp/source
        DEST_DIR: /tmp/dest
        EXTRACT_DIR: /tmp/extract
        BACKUP_INTERVAL: 0
        INITIAL_DELAY: 5s
        EXCLUDES: '*.jar,exclude_dir'
        RCON_PATH: /usr/bin/rcon-cli
        PRUNE_BACKUPS_DAYS: 3
      script: bash ./tests/test.simple.tar.sh
    - name: Test restic handling
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y
          tree
          coreutils
      env:
        SRC_DIR: /tmp/source
        DEST_DIR: /tmp/dest
        RESTIC_REPOSITORY: /tmp/dest
        BACKUP_INTERVAL: 0
        INITIAL_DELAY: 0s
        EXCLUDES: '*.jar,exclude_dir'
        RCON_PATH: /usr/bin/rcon-cli
        RESTIC_PASSWORD: 1234
      script: bash ./tests/test.simple.restic.sh
