#!/bin/bash

case "$1" in
  now)
    ONE_SHOT=true exec /opt/backup-loop.sh ;;
  loop)
    ONE_SHOT=false exec /opt/backup-loop.sh ;;
  *)
    echo "Uknown backup mode. Use now or loop"
    exit 1
    ;;
esac
