version: "3"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
    ports:
      - 25565:25565
    volumes:
      - mc:/data
  backup:
    image: itzg/mc-backup:local
    depends_on:
      mc:
        condition: service_healthy
    environment:
      RCON_HOST: mc
      BACKUP_METHOD: restic
      INITIAL_DELAY: 0
      RESTIC_PASSWORD: password
      RESTIC_REPOSITORY: /backups
      PRUNE_RESTIC_RETENTION: "--keep-daily 7 --keep-weekly 5"
      RESTIC_VERBOSE: true
    volumes:
      - mc:/data:ro
      - backups:/backup

volumes:
  mc: {}
  backups: {}
